### ISSUE TITLE
Why ™?

### ISSUE THREAD

**Issue by fayasnoushad** [nuhmanpk/HandWriting-Bot#1]
Why ™ [here](https://github.com/bughunter0/HandWriting-Bot/blob/3a07a38534f0a452c02e90598ad4e972c3d2d84a/main.py#L2)? TM ( ™ ) For waiting for brand approval from government.

**Comment by nuhmanpk** [comment]
Trying to be a Brand , May be in Future..

**Comment by fayasnoushad** [comment]
> Trying to be a Brand , May be in Future..

Then change brand name to a good name.

Like :- `Nuhman Projects`
